server:
  port: 8888


spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:///D://fun//learn//java//code//project//myconfig//src//main//resources
        #git:
          #uri: https://github.com/o7planning/spring-cloud-config-git-repo-example.git
  profiles:
    active: native
  security:
    user:
      name: admin
      password: admin

