server:
 port: 8999





spring:
  application:
    name: config
   boot:
    admin:
      client:
        url: http://localhost:8888
   application:
      name: eurekaclient
eureka:
  client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      instance:


greeting: sdfsdfsd




management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

