spring:
   application:
      name: eurekaprovider
#ribbon缓存刷新时间
#ribbon.ServerListRefreshInterval=3000
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      registry-fetch-interval-seconds: 1 #定时刷新本地缓存时间
   instance:
         preferIpAddress: true
         leaseRenewalIntervalInSeconds: 1
         leaseExpirationDurationInSeconds: 1 #服务刷新时间配置，每隔这个时间会主动心跳一次，默认30s

server:
  port: 8081